---
title: "proj 1"
author: "Lucy Yin"
date: "6/8/2021"
output: 
 html_document:
  toc: true
  toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Install and load required packages
```{r}
library(httr)
library(jsonlite)
library(tidyverse)
library(knitr)
library(haven)
library(qwraps2)
library(rmarkdown)
library(data.table)
library(kableExtra)
```

## NHL records API
```{r records API}
get.records <- function(table.name, id=NULL, most.recent.id=NULL, ...) {
  base.url <- "https://records.nhl.com/site/api"
  
  if (!is.null(table.name)) {  ## has a table name
    if (table.name %in% ("franchise") & ((!is.null(id)) | (!is.null(most.recent.id)))) {  ## table name is this one and given id
      return ("The table selected cannot be returned with the specified ID and or most recent team ID input.")
    }  
    
    if (is.null(id) & is.null(most.recent.id)) {  ## has table name but no id no most recent team id
      full.url <- paste0(base.url, "/", table.name)
    }
    
    if (table.name %in% c("franchise-team-totals",
                          "franchise-season-records", 
                          "franchise-goalie-records", 
                          "franchise-skater-records") & (!is.null(id)) & (is.null(most.recent.id))) {  ## table name is one of the 4 and given id
      full.url <- paste0(base.url, "/", table.name, "?cayenneExp=franchiseId=", id)
    }
    
    if (table.name %in% c("franchise-team-totals",
                          "franchise-season-records", 
                          "franchise-goalie-records", 
                          "franchise-skater-records") & (!is.null(id)) & (!is.null(most.recent.id))){  ## table name is one of the 4 and given id and given most.recent id
      return (("Only ID and table name are used, please delete most recent team ID entry."))
    }
    
    if (table.name %in% c("franchise-team-totals",
                          "franchise-season-records", 
                          "franchise-goalie-records", 
                          "franchise-skater-records") & (is.null(id)) & (!is.null(most.recent.id))){  ## table name is one of the 4 and only given most.recent id
      return (("Only ID and table name are used, please delete most recent team ID and try using ID instead."))
    }    

    if (table.name %in% ("franchise-detail") & (is.null(id)) & (!is.null(most.recent.id))) {  ## table name is this one and given most recent id
      full.url <- paste0(base.url, "/", table.name, "?cayenneExp=mostRecentTeamId=", most.recent.id)
    }
    
    if (table.name %in% ("franchise-detail") & (!is.null(id)) & (!is.null(most.recent.id))) {  ## table name is this one and given most recent id and id
      return ("Only most recent team ID and table name are used, please delete ID entry.")
    }
    
    if (table.name %in% ("franchise-detail") & (!is.null(id)) & (is.null(most.recent.id))) {  ## table name is this one and given only id
      return ("Please provide the most recent team ID to get results.")
    }  
  
    nfl.records <- GET(full.url)
    nfl.records.txt <- content(nfl.records, "text")  ## convert to JSON text form
    nfl.records.json <- fromJSON(nfl.records.txt, flatten=TRUE)  ## convert to list
    
    return (nfl.records.json$data)
    
  }
  
  else {  ## if no table name
    return ("Table name is invalid.")
  }
}
```

test different scenarios
```{r testing records}
get.records("franchise-goalie-records", id=26)
#get.records("franchise-team-totals", 26, 3)
#get.records("franchise-detail", id=23, most.recent.id = 23)
#get.records("franchise-detail", most.recent.id = 23)

```

## NHL stats API
```{r stats API team stats}
get.stat <- function(modifier = "team.stats", most.recent.id=NULL, ...) {
  base.url2 <- "https://statsapi.web.nhl.com/api/v1/teams"
  
  if (!is.null(most.recent.id)) {  ## modifier given and id is given
    full.url2 <- paste0(base.url2, "/", most.recent.id, "?expand=team.stats")
  }  
  
  else if (is.null(most.rencent.id)) {  ## modifier given and no id
    full.url2 <- paste0(base.url2, "/", "?expand=team.stats")
  }
  
  else if (modifier != "team.stats") {
    return ("team.stats is the only accepted modifier, please try again.")
  }
  
  nfl.stats <- GET(full.url2)
  nfl.stats.txt <- content(nfl.stats, "text")  ## convert to JSON text form
  nfl.stats.json <- fromJSON(nfl.stats.txt, flatten=TRUE)  ## convert to list
    
  return (nfl.stats.json$teams)  
}
```

```{r try out stat1}
#get.stat(most.recent.id = 23)
#get.stat()
#get.stat(26)
```

## Wrapper Function
```{r wrapper 1 mod}
get.nhl.data <- function (table.name=NULL, modifier=NULL, id=NULL, most.recent.id=NULL, season=NULL, ...) {
  # yes table name, yes modifier
  if (!is.null(table.name) & !is.null(modifier)) {
    stop ("Cannot use both table name and modifier to get back information.")
  }
  
  # yes table name
  else if (!is.null(table.name) & is.null(id) & is.null(modifier)) {
    output <- get.records(table.name)
  }  
  
  # yes table name, yes id, no modifier
  else if (!is.null(table.name) & !is.null(id) & is.null(modifier)) {
    output <- get.records(table.name, id)
  }
  
  # yes table name, yes most recent id, no modifier
  else if (!is.null(table.name) & !is.null(most.recent.id) & is.null(modifier)) {
    output <- get.records(table.name, most.recent.id)
  }
  
  else if (!is.null(table.name) & !is.null(id) & !is.null(most.recent.id))
    return("Only ID and table name are used, please delete most recent team ID entry.")
  
  # yes modifier
  else if (!is.null(modifier) & is.null(table.name) & is.null(most.recent.id)) {
    output <- get.stat2(modifier)
  }
  
  # yes modifier, yes most recent id
  else if (!is.null(modifier) & is.null(table.name) & !is.null(most.recent.id)) {
    output <- get.stat2(modifier, most.recent.id)
  }
  
  # yes modifier, yes season
  else if (!is.null(modifier) & is.null(table.name) & !is.null(season)) {
    output <- get.stat2(modifier, season)
  }
  
  # yes modifier, yes multiple most recent id
  else if (!is.null(modifier) & is.null(table.name) & !is.null(most.recent.id) & !is.null(most.recent.id2)) {
    output <- get.stat2(modifier, most.recent.id, most.recent.id2, most.recent.id3, most.recent.id4)
  }
  
  return(output)
}


```


```{r stat API all modifiers}
get.stat2 <- function(modifier, most.recent.id=NULL, season=NULL, most.recent.id2=NULL, most.recent.id3=NULL, most.recent.id4=NULL, ...) {
  base.url3 <- "https://statsapi.web.nhl.com/api/v1/teams"
  
  if (modifier %in% c("team.roster",
                      "person.names",
                      "team.schedule.next", 
                      "team.schedule.previous",  
                      "team.stats") & is.null(most.recent.id)) {  ## modifier is 1 of the 5 and no most recent id given
    
    nfl.stats3 <- GET(paste0(base.url3, "?expand=", modifier))
    nfl.stats3.txt <- content(nfl.stats3, "text")
    nfl.stats3.json<- fromJSON(nfl.stats3.txt, flatten=TRUE)
    
    return (nfl.stats3.json$teams)
  }

  else if (modifier %in% c("team.roster",
                           "person.names",
                           "team.schedule.next",
                           "team.schedule.previous",
                           "team.stats") & !is.null(most.recent.id)) {  ## modifier is 1 of the 5 and yes most recent id

    nfl.stats3 <- GET(paste0(base.url3, "/", most.recent.id, "?expand=", modifier))
    nfl.stats3.txt <- content(nfl.stats3, "text")
    nfl.stats3.json<- fromJSON(nfl.stats3.txt, flatten=TRUE)
    
    return (nfl.stats3.json$teams)
  }
  
  else if (modifier %in% ("team.roster&season") & is.null(most.recent.id) & !is.null(season)) {  ## modifier is this and no most recent id and yes season
    nfl.stats3 <- GET(paste0(base.url3, "?expand=", modifier, "=", season))
    nfl.stats3.txt <- content(nfl.stats3, "text")
    nfl.stats3.json<- fromJSON(nfl.stats3.txt, flatten=TRUE)
    
    return (nfl.stats3.json$teams)
  }
  
  else if (modifier %in% ("team.roster&season") & !is.null(most.recent.id) & !is.null(season)) {  ## modifier is this and yes most recent id and yes season
    nfl.stats3 <- GET(paste0(base.url3, "/", most.recent.id, "?expand=", modifier, "=", season))
    nfl.stats3.txt <- content(nfl.stats3, "text")
    nfl.stats3.json<- fromJSON(nfl.stats3.txt, flatten=TRUE)
    
    return (nfl.stats3.json$teams)
  }  
  
  else if (modifier %in% ("team.roster&season") & is.null(season)) {  ## modifier is this and no season
    return ("Must provide a season input, please try again.")
  }    

    
  else if (modifier %in% ("teamId") & !is.null(c(most.recent.id, most.recent.id2, most.recent.id3, most.recent.id4))) {  ## modifier is this and multiple most recent team id given
    
    nfl.stats3 <- GET(paste0(base.url3, "?", modifier, "=", 
                             paste(most.recent.id, most.recent.id2, most.recent.id3, most.recent.id4, sep = ",")))
    nfl.stats3.txt <- content(nfl.stats3, "text")
    nfl.stats3.json<- fromJSON(nfl.stats3.txt, flatten=TRUE)
    
    return (nfl.stats3.json$teams)
  }
  
  
  else if (modifier %in% ("statsSingleSeasonPlayoffs") & is.null(most.recent.id)) {  ## modifier is this and no most recent id given
    nfl.stats3 <- GET(paste0(base.url3, "?stats=", modifier))
    nfl.stats3.txt <- content(nfl.stats3, "text")
    nfl.stats3.json<- fromJSON(nfl.stats3.txt, flatten=TRUE)
    
    return (nfl.stats3.json$teams)
  }
  
  else if (modifier %in% ("statsSingleSeasonPlayoffs") & !is.null(most.recent.id)) {  ## modifier is this and yes most recent id
    nfl.stats3 <- GET(paste0(base.url3, "/", most.recent.id, "?stats=", modifier))
    nfl.stats3.txt <- content(nfl.stats3, "text")
    nfl.stats3.json<- fromJSON(nfl.stats3.txt, flatten=TRUE)
    
    return (nfl.stats3.json$teams)
  }  


  else {
    stop ("Invalid input, please try again.")  
  }
}
```

try out function
```{r testing stat}
get.stat2("team.roster&season", 12, 20142015)
get.stat2("team.roster&season", NULL, 20142015)
get.stat2("person.names")
get.stat2("teamId", most.recent.id = 12, most.recent.id2 = 21)

```
## Wrapper Function
```{r wrapper all mod}
get.nhl.data <- function (table.name=NULL, modifier=NULL, id=NULL, most.recent.id=NULL, season=NULL, ...) {
  # yes table name, yes modifier
  if (!is.null(table.name) & !is.null(modifier)) {
    stop ("Cannot use both table name and modifier to get back information.")
  }
  
  # yes table name
  else if (!is.null(table.name) & is.null(id) & is.null(modifier)) {
    output <- get.records(table.name)
  }  
  
  # yes table name, yes id, no modifier
  else if (!is.null(table.name) & !is.null(id) & is.null(modifier)) {
    output <- get.records(table.name, id)
  }
  
  # yes table name, yes most recent id, no modifier
  else if (!is.null(table.name) & !is.null(most.recent.id) & is.null(modifier)) {
    output <- get.records(table.name, most.recent.id)
  }
  
  else if (!is.null(table.name) & !is.null(id) & !is.null(most.recent.id))
    return("Only ID and table name are used, please delete most recent team ID entry.")
  
  # yes modifier
  else if (!is.null(modifier) & is.null(table.name) & is.null(most.recent.id)) {
    output <- get.stat2(modifier)
  }
  
  # yes modifier, yes most recent id
  else if (!is.null(modifier) & is.null(table.name) & !is.null(most.recent.id)) {
    output <- get.stat2(modifier, most.recent.id)
  }
  
  # yes modifier, yes season
  else if (!is.null(modifier) & is.null(table.name) & !is.null(season)) {
    output <- get.stat2(modifier, season)
  }
  
  # yes modifier, yes multiple most recent id
  else if (!is.null(modifier) & is.null(table.name) & !is.null(most.recent.id) & !is.null(most.recent.id2)) {
    output <- get.stat2(modifier, most.recent.id, most.recent.id2, most.recent.id3, most.recent.id4)
  }
  
  return(output)
}
```

```{r try wrapper all mod}
get.nhl.data(table.name = "franchise-team-totals")  ## only id used
get.nhl.data(modifier = "person.names", most.recent.id = 12, season = 20142015)

```

## Grabbing data and analyzing
```{r grabbing data from 2 tables}
# get all information from "franchise-team-totals"
team.total.raw <- get.nhl.data(table.name = "franchise-team-totals") %>% rename(abbreviation = triCode)

# combine the duplicate rows in team.total so that each team only has 1 row (instead of 2+ rows)

# convert into a data table format
team.total.dt <- as.data.table(team.total.raw)
# identify which columns are numeric 
numeric_cols <- which(sapply(team.total.dt, is.numeric))
# sum up all the values and combine duplicate rows into 1
team.total <- team.total.dt[, lapply(.SD, FUN = sum), by = abbreviation, .SDcols = numeric_cols]
write_csv(team.total,"new.team.total.csv")

# get division data for different teams from "team.stats"
division <- get.nhl.data(modifier = "team.stats") %>% select(franchiseId, name, abbreviation, teamName, venue.name, venue.city, division.id, division.name, conference.id, conference.name)
```

```{r combining tables}
# combine the 2 tables together using "abbreviation" as index. (there are instances where the same franchiseId were used for many different teams, so using "abbreviation" as index)
new.data <- left_join(team.total, division, by="abbreviation")
new.data.na <- left_join(team.total, division, by="abbreviation")
write_csv(new.data, "new.data.csv")

head(new.data)
```

## Read data from 2 different API's
```{r read data from 2 api}
franchise.data <- get.records("franchise"); franchise.data
franchise.data <- franchise.data %>% select(id, mostRecentTeamId, teamCommonName, teamAbbrev, teamPlaceName)

goalie.data.hurricanes <- get.records("franchise-goalie-records", id=26) %>% select(activePlayer, firstName, lastName, gamesPlayed, wins, ties, losses, seasons, shutouts, mostShotsAgainstOneGame, mostGoalsAgainstOneGame, mostSavesOneGame, mostShutoutsOneSeason, mostWinsOneSeason)
```

## Create new variables
```{r new variable}

# replace NA as 0 in new.data
new.data[is.na(new.data)] = 0


new.data$perc.total.games.win <- (new.data$wins / new.data$gamesPlayed * 100) %>% round(2)

new.data$perc.total.games.loss <- (new.data$losses / new.data$gamesPlayed * 100) %>% round(2)

new.data$perc.home.win <- (new.data$homeWins / (new.data$homeLosses + new.data$homeOvertimeLosses + new.data$homeTies + new.data$homeWins) *100) %>% round(2)

new.data$perc.home.loss <- (new.data$homeLosses / (new.data$homeLosses + new.data$homeOvertimeLosses + new.data$homeTies + new.data$homeWins) *100) %>% round(2)

new.data$perc.road.win <- (new.data$roadWins / (new.data$roadLosses + new.data$roadOvertimeLosses + new.data$roadTies + new.data$roadWins) *100) %>% round(2)

new.data$perc.road.loss <- (new.data$roadLosses / (new.data$roadLosses + new.data$roadOvertimeLosses + new.data$roadTies + new.data$roadWins) *100) %>% round(2)


```


## Contingency Tables
```{r contingency table active/inactive}
goalie.data <- get.records("franchise-goalie-records") %>% select(franchiseName, activePlayer, firstName, lastName, gamesPlayed, wins, ties, losses, seasons, shutouts, mostShotsAgainstOneGame, mostGoalsAgainstOneGame, mostSavesOneGame, mostShutoutsOneSeason, mostWinsOneSeason)
goalie.data
table(goalie.data$franchiseName)
table(goalie.data$activePlayer)

# find the count of active/inactive players by franchise
contingency.table1 <- table(goalie.data$franchiseName, goalie.data$activePlayer) %>% kable(caption = "Contingency Table of Active (TRUE) / Inactive (FALSE) Player Count by Franchise")

# find the proportion by margin=1 (rows)
contingency.table1.prop <- table(goalie.data$franchiseName, goalie.data$activePlayer) %>% prop.table(margin=1)*100
contingency.table1.prop %>% kable(caption = "Proportion of Active (TRUE) / Inactive (FALSE) Players by Franchise")
```

```{r contingency table wins and division}
table(new.data$division.name)
table(new.data$wins)

# find the count of franchises w/i a division that had over 2000 wins
contingency.table2 <- table(new.data$division.name, new.data$wins>2000) %>% kable(caption = "Contingency Table of Number of Franchises in a Division that had Over 200 Wins")

# find the proportion by margin=2 (columns)
contingency.table2.prop <- table(new.data$division.name, new.data$wins>2000) %>% prop.table(margin=2)*100
contingency.table2.prop %>% kable(caption = "Proportion of Over 200 Win Teams By Division")

```

## Plots
### Bar plot
```{r plot - bar}
new.data.no.na <- new.data.na %>% drop_na(division.name)
ggplot(data = new.data.no.na, aes(x = division.name)) + 
  geom_bar(aes(fill = as.factor(conference.name)), position = "dodge") + 
  labs(x = "Division", title = "Bar Plot of Number of Franchise in Each Division") + 
  scale_fill_discrete(name = "Conference Name", labels = c("Eastern Conference", "Western Conference"))
```

## Individual tables for reference 
```{r franchise, include=FALSE}
franchise <- GET("https://records.nhl.com/site/api/franchise")
franchise.text <- content(franchise, "text")
franchise.json <- fromJSON(franchise.text, flatten=TRUE)
franchise.json$data
write.csv(franchise.json$data,"franchise.csv", row.names = FALSE)
```

```{r team id index, include=FALSE}
team.id.index <- franchise.json$data %>% select("id", "mostRecentTeamId", "fullName", "teamAbbrev", "teamCommonName", "teamPlaceName")
team.id.index
```

```{r team totals, include=FALSE}
franchise_team_totals <- GET("https://records.nhl.com/site/api/franchise-team-totals")
franchise_team_totals.text <- content(franchise_team_totals, "text")
franchise_team_totals.json <- fromJSON(franchise_team_totals.text, flatten=TRUE)
franchise_team_totals.json$data
write.csv(franchise_team_totals.json$data,"franchise-team-total.csv", row.names = FALSE)

```

```{r team totals id, include=FALSE}
franchise_team_totals2 <- GET("https://records.nhl.com/site/api/franchise-team-totals?cayenneExp=franchiseId=26")
franchise_team_totals2.text <- content(franchise_team_totals2, "text")
franchise_team_totals2.json <- fromJSON(franchise_team_totals2.text, flatten=TRUE)
franchise_team_totals2.json$data
```



```{r season, include=FALSE}
franchise_season <- GET("https://records.nhl.com/site/api/franchise-season-records?cayenneExp=franchiseId=26")
franchise_season.text <- content(franchise_season, "text")
franchise_season.json <- fromJSON(franchise_season.text, flatten=TRUE)
franchise_season.json$data
write.csv(franchise_season.json$data,"franchise-season-records.csv", row.names = FALSE)

```

```{r goalie, include=FALSE}
franchise_goalie <- GET("https://records.nhl.com/site/api/franchise-goalie-records?cayenneExp=franchiseId=26")
franchise_goalie.text <- content(franchise_goalie, "text")
franchise_goalie.json <- fromJSON(franchise_goalie.text, flatten=TRUE)
franchise_goalie.json$data
write.csv(franchise_goalie.json$data,"franchise-goalie-records.csv", row.names = FALSE)

```

```{r skater, include=FALSE}
franchise_skater <- GET("https://records.nhl.com/site/api/franchise-skater-records?cayenneExp=franchiseId=26")
franchise_skater.text <- content(franchise_skater, "text")
franchise_skater.json <- fromJSON(franchise_skater.text, flatten=TRUE)
franchise_skater.json$data
write.csv(franchise_skater.json$data,"franchise-skater-records.csv", row.names = FALSE)

```

```{r franchise detail, include=FALSE}
franchise_detail <- GET("https://records.nhl.com/site/api/franchise-detail?cayenneExp=mostRecentTeamId=26")
franchise_detail.text <- content(franchise_detail, "text")
franchise_detail.json <- fromJSON(franchise_detail.text, flatten=TRUE)
franchise_detail.json$data
write.csv(franchise_detail.json$data,"franchise-details.csv", row.names = FALSE)

```

## NHL stats API

```{r team roster, include=FALSE}
team_roster <- GET("https://statsapi.web.nhl.com/api/v1/teams?expand=team.roster")
team_roster.text <- content(team_roster, "text")
team_roster.json <- fromJSON(team_roster.text, flatten=TRUE)
team_roster.json$teams
#write.table(team_roster.json$teams,"team-roster.csv", row.names = FALSE)
```

```{r person names, include=FALSE}
person.names <- GET("https://statsapi.web.nhl.com/api/v1/teams?expand=person.names")
person.names.text <- content(person.names, "text")
person.names.json <- fromJSON(person.names.text, flatten=TRUE)
person.names.json$teams
```

```{r schedule next, include=FALSE}
schedule.next <- GET("https://statsapi.web.nhl.com/api/v1/teams?expand=team.schedule.next")
schedule.next.text <- content(schedule.next, "text")
schedule.next.json <- fromJSON(schedule.next.text, flatten=TRUE)
schedule.next.json$teams
```

```{r schedule previous, include=FALSE}
schedule.prev <- GET("https://statsapi.web.nhl.com/api/v1/teams?expand=team.schedule.previous")
schedule.prev.text <- content(schedule.prev, "text")
schedule.prev.json <- fromJSON(schedule.prev.text, flatten=TRUE)
schedule.prev.json$teams
```

```{r team stats, include=FALSE}
team_stats <- GET("https://statsapi.web.nhl.com/api/v1/teams?expand=team.stats")
team_stats.text <- content(team_stats, "text")
team_stats.json <- fromJSON(team_stats.text, flatten=TRUE)
team_stats.json$teams
#write.csv(team_stats.json$teams,"team-stats.csv", row.names = FALSE)
```

```{r team stats id, include=FALSE}
team_stats.id <- GET("https://statsapi.web.nhl.com/api/v1/teams/12?expand=team.stats")
team_stats.id.text <- content(team_stats.id, "text")
team_stats.id.json <- fromJSON(team_stats.id.text, flatten=TRUE)
team_stats.id.json$teams
```

```{r roster season, include=FALSE}
roster.season <- GET("https://statsapi.web.nhl.com/api/v1/teams?expand=team.roster&season=20142015")
roster.season.text <- content(roster.season, "text")
roster.season.json <- fromJSON(roster.season.text, flatten=TRUE)
roster.season.json$teams
```

```{r teamId, include=FALSE}
teamId <- GET("https://statsapi.web.nhl.com/api/v1/teams/?teamId=12,21")
teamId.text <- content(teamId, "text")
teamId.json <- fromJSON(teamId.text, flatten=TRUE)
teamId.json$teams
```

```{r single season, include=FALSE}
single.season <- GET("https://statsapi.web.nhl.com/api/v1/teams?stats=statsSingleSeasonPlayoffs")
single.season.text <- content(single.season, "text")
single.season.json <- fromJSON(single.season.text, flatten=TRUE)
single.season.json$teams
```